language: php

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - '7.2'

before_script:
  - phpenv config-rm xdebug.ini
  - composer self-update

install:
  - make install

script:
  - make test
