parameters:
    oauth_client_id: '%env(OAUTH_SLACK_CLIENT_ID)%'
    oauth_client_secret: '%env(OAUTH_SLACK_CLIENT_SECRET)%'
    app_data_path: '%kernel.root_dir%/../data/prod'
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $oauthClientId: '%env(OAUTH_SLACK_CLIENT_ID)%'
            $oauthClientSecret: '%env(OAUTH_SLACK_CLIENT_SECRET)%'
            $dataPath: '%app_data_path%'

    _instanceof:
        App\Whhato\LoaderInterface:
            tags: ['app_loader']

    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Whhato\Whhato:
        $loaders: !tagged app_loader

    App\Whhato\DoctrineLoader:
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments: ['App\Whhato\DateMessage']
